-- Do not touch these codes as much as possible (touch them if you are familiar and confident)

Words = {
    "Fallout Menu",
    "Fallout",
    "Cheat",
    "Eulen",
    "Weapon Menu",
    "Self Menu",
    "Vehicle Menu",
    "God Mode",
    "Semi God Mode",
    "Aimbot",
    "Teleport to waypoint",
    "Fast Run",
    "Infinite Stamina",
    "Infinite Ammo",
    "Nuke",
    "Destroy ESX",
    "Lua Executor",
    "Super Jump",
    "Give All Weapons",
    "Remove all weapons",
    "AntiAim",
    "Trigger Bot",
    "Trigger bot",
    "Aim bot",
    "Explode Everyone",
    "Give Money",
    "Lynx Revolution",
    "Lynx Menu",
    "Atomic",
    "Noclip",
    "Unknowncheats",
    "Watermalone",
    "Brutan",
    "Dopamine",
    "Tiago Menu",
    "Lua options",
    "Self Options",
    "Absolute",
    "Matrix",
    "Troll Menu",
    "Troll Features",
    "Panic Button",
    "Kill menu",
    "Destroy Menu",
    "34ByTe Community",
    "Powerfulsokin",
    "Falcon",
    "Cage Players",
    "Rage bot",
    "Unlimited ammo",
    "One shot",
    "All players",
    "Skull Revolution"
}
