-- Do not touch these codes as much as possible (touch them if you are familiar and confident)

Explosion = {
    [0] = { NAME = "Grenade", Log = true, Punishment = "BAN" },
    [1] = { NAME = "GrenadeLauncher", Log = true, Punishment = "BAN" },
    [2] = { NAME = "Stick Bomb", Log = true, Punishment = false },
    [3] = { NAME = "Molotov", Log = true, Punishment = "BAN" },
    [4] = { NAME = "Rocket", Log = true, Punishment = "BAN" },
    [5] = { NAME = "TankShell", Log = true, Punishment = "BAN" },
    [6] = { NAME = "Hi_Octane", Log = false, Punishment = false },
    [7] = { NAME = "Car", Log = false, Punishment = false },
    [8] = { NAME = "Plance", Log = false, Punishment = false },
    [9] = { NAME = "PetrolPump", Log = false, Punishment = false },
    [10] = { NAME = "Bike", Log = false, Punishment = false },
    [11] = { NAME = "Dir_Steam", Log = false, Punishment = false },
    [12] = { NAME = "Dir_Flame", Log = false, Punishment = false },
    [13] = { NAME = "Dir_Water_Hydrant", Log = false, Punishment = false },
    [14] = { NAME = "Dir_Gas_Canister", Log = false, Punishment = false },
    [15] = { NAME = "Boat", Log = false, Punishment = false },
    [16] = { NAME = "Ship_Destroy", Log = false, Punishment = false },
    [17] = { NAME = "Truck", Log = false, Punishment = false },
    [18] = { NAME = "Bullet", Log = true, Punishment = "BAN" },
    [19] = { NAME = "SmokeGrenadeLauncher", Log = true, Punishment = "BAN" },
    [20] = { NAME = "SmokeGrenade", Log = false, Punishment = false },
    [21] = { NAME = "BZGAS", Log = false, Punishment = false },
    [22] = { NAME = "Flare", Log = false, Punishment = false },
    [23] = { NAME = "Gas_Canister", Log = false, Punishment = false },
    [24] = { NAME = "Extinguisher", Log = false, Punishment = false },
    [25] = { NAME = "Programmablear", Log = false, Punishment = false },
    [26] = { NAME = "Train", Log = false, Punishment = false },
    [27] = { NAME = "Barrel", Log = false, Punishment = false },
    [28] = { NAME = "PROPANE", Log = false, Punishment = false },
    [29] = { NAME = "Blimp", Log = false, Punishment = false },
    [30] = { NAME = "Dir_Flame_Explode", Log = false, Punishment = false },
    [31] = { NAME = "Tanker", Log = false, Punishment = false },
    [32] = { NAME = "PlaneRocket", Log = true, Punishment = "BAN" },
    [33] = { NAME = "VehicleBullet", Log = false, Punishment = false },
    [34] = { NAME = "Gas_Tank", Log = true, Punishment = "WARN" },
    [35] = { NAME = "FireWork", Log = false, Punishment = false },
    [36] = { NAME = "SnowBall", Log = false, Punishment = false },
    [37] = { NAME = "Valkyrie_Cannon", Log = true, Punishment = "BAN" }
}
