-- Do not touch these codes as much as possible (touch them if you are familiar and confident)

Commands = {
    "chocolate",
    "haha",
    "lol",
    "panickey",
    "killmenu",
    "panik",
    "ssssss",
    "brutan",
    "panic",
    "brutanpremium",
    "hammafia",
    "purgemenu",
    "hamhaxia",
    "redstonia",
    "hoax",
    "desudo",
    "jd",
    "ham",
    "lua options",
    "God Mode",
    "Maestro",
    "FunCtionOk",
    "lynx9_fixed",
    "Fucked",
    "injected",
    "vRP",
    "deleted due to u being a nigger",
    "Dopamine injected successfully",
    "parent menu doesn",
    "www.d0pamine.xyz",
    "d0pamine v1.1 by Nertigel",
    "d0pamine",
    "lynx",
    "FOriv gay",
    "TiagoModz#1478",
    "tiago",
    "TiagoModz",
    "dopamine",
    "dopamina",
    "Nertigel: This server is protected and the menu is not gonna work here.",
    "Information",
    "[dopamine]",
    "KP",
    "opk",
    "jolmany",
    "SovietH4X",
    "injection",
    "dopmain",
    "jailall",
    "serverfck",
    "banall",
    "getcar",
    "incar",
    "panickey",
}
